### ISSUE TITLE
Consider migrating to Maven repository

### ISSUE THREAD

**Issue by yamin8000** [supabase-community/postgrest-kt#3]
# Chore

## Describe the chore

jCenter is currently deprecated and artifacts can only be downloaded till 2022-02-01, consider migrating to jitpack or even better maven central.

## Additional context

[more info here](https://developer.android.com/studio/build/jcenter-migration)

**Comment by jlengrand** [comment]
Is it not already there? https://mvnrepository.com/artifact/io.supabase/postgrest-kt. 

I might be wrong but that looks like the reight package?

**Comment by yamin8000** [comment]
> Is it not already there? https://mvnrepository.com/artifact/io.supabase/postgrest-kt.
> 
> I might be wrong but that looks like the right package?

No, It's not there.
Yes, You're looking at the right package. However, This is not hosted in mvn repository and the artifact is in JCenter according to [this](https://mvnrepository.com/artifact/io.supabase/postgrest-kt/0.2.0) which is currently deprecated.
JCenter is read-only since March 2021 and would remain in that order [indefinitely](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) so for further developments, it's best to migrate to mvn repository.

![image](https://user-images.githubusercontent.com/5001708/147854395-06161891-0abb-4ff9-8175-1a2553862641.png)

**Comment by jlengrand** [comment]
Ha, right my bad indeed I didn't realize

**Comment by jlengrand** [comment]
Just adding my 2 cent, the file doesn't even seem to be available at all any more as far as I can tell : 

Trying to [access directly](https://jcenter.bintray.com/io/supabase/postgrest-kt/0.2.0/postgrest-kt-0.2.0.jar) gives me  a 403.

Trying to download via Gradle : 

```
Execution failed for task ':compileKotlin'.
> Error while evaluating property 'filteredArgumentsMap' of task ':compileKotlin'
   > Could not resolve all files for configuration ':compileClasspath'.
      > Could not find io.supabase:postgrest-kt:0.2.0.
        Searched in the following locations:
          - https://dl.google.com/dl/android/maven2/io/supabase/postgrest-kt/0.2.0/postgrest-kt-0.2.0.pom
          - https://repo.maven.apache.org/maven2/io/supabase/postgrest-kt/0.2.0/postgrest-kt-0.2.0.pom
          - https://maven.pkg.jetbrains.space/public/p/compose/dev/io/supabase/postgrest-kt/0.2.0/postgrest-kt-0.2.0.pom
        Required by:
            project :
```

**Comment by yamin8000** [comment]
@jlengrand Yeah same 403 error for me. So then migrating to mvn is a most.

**Comment by jlengrand** [comment]
@yamin8000 I was a bit fast, (1st of January after all :)).

The error disappears for me if I add `jcenter()` in the list of repositories in my gradle file: 

```
repositories {
    ...
    jcenter()
    ...
}
```
